### PR TITLE
Refactor Swap, and fix harmonic flip

### LINKED ISSUE #110: Test Harmonic Triangulations on Gaussian and Uniform points
Try to match paper results.

Also, the armadillo starts from CGAL.

### PR DESCRIPTION
**Pull request by jiangzhongshi**
closes #110

### CODE REVIEW

File: app/harmonic_tet/HarmonicTet.cpp [hunk 1]
```diff
@@ -264,25 +261,78 @@ void HarmonicTet::output_mesh(std::string file) const
...
     auto collect_all_ops = std::vector<std::pair<std::string, Tuple>>();
     for (auto& loc : get_edges()) collect_all_ops.emplace_back("edge_swap", loc);
 
-    auto executor = wmtk::ExecutePass<HarmonicTet, wmtk::ExecutionPolicy::kPartition>();
+    auto executor = wmtk::ExecutePass<HarmonicTet, wmtk::ExecutionPolicy::kSeq>();
     executor.renew_neighbor_tuples = renewal_all;
-    executor.priority =
-        [](auto& m, auto op, const wmtk::TetMesh::Tuple& t) -> double { // using delta trace
+
+    executor.priority = [&swap_3_2, &swap_2_3](auto& m, auto op, const wmtk::TetMesh::Tuple& t)
```
Comment (jiangzhongshi) [inline app/harmonic_tet/HarmonicTet.cpp:334]:
```suggestion
    executor.priority = [](auto& m, auto op, const wmtk::TetMesh::Tuple& t)
```
